version: "3.7"

services:
    hfpy:
        image: hfpy_pg:1015
        container_name: hfpy
        restart: always
        environment:
            # 策略信号入库使用
            - "pg_config: "
        volumes: 
            # 个人策略文件夹
            - ./strategies:/hfpy/strategies
            # hfpy配置文件
            - ./config.yml:/hfpy/config.yml
        
# docker pull haifengat/hfpy && docker tag haifengat/hfpy haifengat/hfpy:`date '+%m%d'` && docker push haifengat/hfpy:`date '+%m%d'`

