version: "3.7"

services:
    hf_py:
        image: haifengat/hfpy
        container_name: hf_py
        restart: always
        environment:
            - TZ=Asia/Shanghai
            # 当日分钟与实时分钟
            - redis_addr="172.19.129.98:16379"
            # 分钟数据,没配置zmq时使用
            - pg_min=postgresql://postgres:12345@hf_py_pg:5432/postgres
            # 策略信号入库使用
            - pg_order=postgresql://postgres:12345@hf_py_pg:5432/postgres
        volumes:
            # 个人策略文件夹
            - ./strategies:/hfpy/strategies
            # hfpy配置
            - ./config:/hfpy/config
        depends_on:
            - hf_py_pg
    hf_py_pg:
        image: postgres:12-alpine
        container_name: hf_py_pg
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - POSTGRES_PASSWORD=12345
        ports:
            - "20032:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data

# docker pull haifengat/hfpy && docker tag haifengat/hfpy haifengat/hfpy:`date '+%m%d'` && docker push haifengat/hfpy:`date '+%m%d'`
