version: "3.7"

services:
    hfpy:
        image: haifengat/hfpy
        container_name: hfpy
        restart: always
        volumes: 
            # 个人策略文件夹
            - ./strategies:/home/strategies
            # 配置文件
            - ./config_real.yml:/home/config.yml:ro
        
