version: "3.7"

services:
    hfpy:
        image: haifengat/hfpy
        container_name: hfpy
        restart: always
        environment:
            # config.yml所在目录
            config_path: /home/config/
        volumes: 
            # 个人策略文件夹
            - ./strategies:/home/strategies
            # hfpy配置文件
            - ./config.yml:/home/config/config.yml
        
